### ISSUE TITLE
The build doesn't work on Mac OS M1

### ISSUE THREAD

**Issue by dlucanu** [boogie-org/forro#1]
The build process asks for  'Microsoft.NETCore.App', version '3.0.0' (arm64), which is not available.|
Is it any chance to have a version working on arm 64 architecture?
Thanks.
Dorel Lucanu

**Comment by bkragl** [comment]
@dlucanu I don't have a machine to test, but I think the upgrade to .NET 6.0 should work for you. Please reopen if not.
